name = "CMDV"
uid = "PressureMakesDiamondsOrWhat-faf-2025-510"
version = 510
copyright = "Forever"
description = "Forged Alliance Forever Mod - Conservation of Momentum Dynamics Variation"
author = "CubeMD"
selectable = true
enabled = true
exclusive = true
ui_only = false
conflicts = { "eternal-pack-shared_mouse_2" }