name = "Multiplayer Save FA2"
uid = "f1aaf5c9-8bbd-43e2-8f6a-999999900012"
version = 12
copyright = "Free for distribution and use with Supreme Commander. Check website link for commercial use restrictions and licensing enquiries."
description = "This module allows saving multiplayer games. Designed to fix some bugs with newer FAF versions, and packages dependencies with it. "
author = "SpliFF,SpiteandHatred"
url = "http://www.warriorhut.org/forged_alliance/multiplayer_save"
icon = "/mods/Multiplayer Save FA 2/icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = {  }